# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'companiesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_companiesWindow(object):
    def setupUi(self, companiesWindow):
        companiesWindow.setObjectName("companiesWindow")
        companiesWindow.resize(350, 350)
        companiesWindow.setMinimumSize(QtCore.QSize(350, 350))
        companiesWindow.setMaximumSize(QtCore.QSize(350, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("View/icons/companies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        companiesWindow.setWindowIcon(icon)
        self.companyNameEdit = QtWidgets.QLineEdit(companiesWindow)
        self.companyNameEdit.setGeometry(QtCore.QRect(10, 205, 150, 30))
        self.companyNameEdit.setObjectName("companyNameEdit")
        self.companyLabel = QtWidgets.QLabel(companiesWindow)
        self.companyLabel.setGeometry(QtCore.QRect(10, 180, 150, 15))
        self.companyLabel.setObjectName("companyLabel")
        self.typeLabel = QtWidgets.QLabel(companiesWindow)
        self.typeLabel.setGeometry(QtCore.QRect(10, 245, 150, 15))
        self.typeLabel.setObjectName("typeLabel")
        self.companyTypeComboBox = QtWidgets.QComboBox(companiesWindow)
        self.companyTypeComboBox.setGeometry(QtCore.QRect(10, 265, 150, 22))
        self.companyTypeComboBox.setObjectName("companyTypeComboBox")
        self.companyTypeComboBox.addItem("")
        self.companyTypeComboBox.addItem("")
        self.domainLabel = QtWidgets.QLabel(companiesWindow)
        self.domainLabel.setGeometry(QtCore.QRect(190, 180, 150, 15))
        self.domainLabel.setObjectName("domainLabel")
        self.DomainEdit = QtWidgets.QLineEdit(companiesWindow)
        self.DomainEdit.setGeometry(QtCore.QRect(190, 205, 150, 30))
        self.DomainEdit.setObjectName("DomainEdit")
        self.CompanyDomainComboBox = QtWidgets.QComboBox(companiesWindow)
        self.CompanyDomainComboBox.setGeometry(QtCore.QRect(190, 265, 150, 22))
        self.CompanyDomainComboBox.setObjectName("CompanyDomainComboBox")
        self.companyDomainLabel = QtWidgets.QLabel(companiesWindow)
        self.companyDomainLabel.setGeometry(QtCore.QRect(190, 245, 150, 15))
        self.companyDomainLabel.setObjectName("companyDomainLabel")
        self.addCompanyButton = QtWidgets.QPushButton(companiesWindow)
        self.addCompanyButton.setGeometry(QtCore.QRect(10, 300, 150, 30))
        self.addCompanyButton.setObjectName("addCompanyButton")
        self.addDomainButton = QtWidgets.QPushButton(companiesWindow)
        self.addDomainButton.setGeometry(QtCore.QRect(190, 300, 150, 30))
        self.addDomainButton.setObjectName("addDomainButton")
        self.line = QtWidgets.QFrame(companiesWindow)
        self.line.setGeometry(QtCore.QRect(175, 180, 16, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.treeView = QtWidgets.QTreeView(companiesWindow)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 331, 161))
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)

        self.retranslateUi(companiesWindow)
        QtCore.QMetaObject.connectSlotsByName(companiesWindow)

    def retranslateUi(self, companiesWindow):
        _translate = QtCore.QCoreApplication.translate
        companiesWindow.setWindowTitle(_translate("companiesWindow", "Компании"))
        self.companyLabel.setText(_translate("companiesWindow", "Компания"))
        self.typeLabel.setText(_translate("companiesWindow", "Тип"))
        self.companyTypeComboBox.setItemText(0, _translate("companiesWindow", "partner"))
        self.companyTypeComboBox.setItemText(1, _translate("companiesWindow", "client"))
        self.domainLabel.setText(_translate("companiesWindow", "Связать домен"))
        self.companyDomainLabel.setText(_translate("companiesWindow", "С компанией"))
        self.addCompanyButton.setText(_translate("companiesWindow", "Добавить компанию"))
        self.addDomainButton.setText(_translate("companiesWindow", "Связать"))
