# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configWindow(object):
    def setupUi(self, configWindow):
        configWindow.setObjectName("configWindow")
        configWindow.resize(285, 230)
        configWindow.setMinimumSize(QtCore.QSize(285, 230))
        configWindow.setMaximumSize(QtCore.QSize(285, 230))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        configWindow.setWindowIcon(icon)
        self.HostLabel = QtWidgets.QLabel(configWindow)
        self.HostLabel.setGeometry(QtCore.QRect(10, 10, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.HostLabel.setFont(font)
        self.HostLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HostLabel.setAutoFillBackground(False)
        self.HostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HostLabel.setObjectName("HostLabel")
        self.PortLabel = QtWidgets.QLabel(configWindow)
        self.PortLabel.setGeometry(QtCore.QRect(10, 50, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PortLabel.setFont(font)
        self.PortLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PortLabel.setObjectName("PortLabel")
        self.UserLabel = QtWidgets.QLabel(configWindow)
        self.UserLabel.setGeometry(QtCore.QRect(10, 90, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.UserLabel.setFont(font)
        self.UserLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UserLabel.setObjectName("UserLabel")
        self.PasswordLabel = QtWidgets.QLabel(configWindow)
        self.PasswordLabel.setGeometry(QtCore.QRect(10, 130, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.HostEdit = QtWidgets.QLineEdit(configWindow)
        self.HostEdit.setGeometry(QtCore.QRect(150, 17, 115, 30))
        self.HostEdit.setObjectName("HostEdit")
        self.PortEdit = QtWidgets.QLineEdit(configWindow)
        self.PortEdit.setGeometry(QtCore.QRect(150, 57, 115, 30))
        self.PortEdit.setObjectName("PortEdit")
        self.UserEdit = QtWidgets.QLineEdit(configWindow)
        self.UserEdit.setGeometry(QtCore.QRect(150, 97, 115, 30))
        self.UserEdit.setObjectName("UserEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(configWindow)
        self.PasswordEdit.setGeometry(QtCore.QRect(150, 137, 115, 30))
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.DownloadButton = QtWidgets.QPushButton(configWindow)
        self.DownloadButton.setGeometry(QtCore.QRect(10, 180, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DownloadButton.setFont(font)
        self.DownloadButton.setObjectName("DownloadButton")
        self.OutputLabel = QtWidgets.QLabel(configWindow)
        self.OutputLabel.setGeometry(QtCore.QRect(150, 180, 121, 41))
        self.OutputLabel.setText("")
        self.OutputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLabel.setObjectName("OutputLabel")

        self.retranslateUi(configWindow)
        QtCore.QMetaObject.connectSlotsByName(configWindow)

    def retranslateUi(self, configWindow):
        _translate = QtCore.QCoreApplication.translate
        configWindow.setWindowTitle(_translate("configWindow", "Config"))
        self.HostLabel.setText(_translate("configWindow", "Host:"))
        self.PortLabel.setText(_translate("configWindow", "Port:"))
        self.UserLabel.setText(_translate("configWindow", "User:"))
        self.PasswordLabel.setText(_translate("configWindow", "Password:"))
        self.DownloadButton.setText(_translate("configWindow", "Загрузить"))
