# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DBWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBWindow(object):
    def setupUi(self, DBWindow):
        DBWindow.setObjectName("DBWindow")
        DBWindow.resize(500, 200)
        DBWindow.setMinimumSize(QtCore.QSize(500, 200))
        DBWindow.setMaximumSize(QtCore.QSize(500, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DBWindow.setWindowIcon(icon)
        self.CreateDB = QtWidgets.QPushButton(DBWindow)
        self.CreateDB.setGeometry(QtCore.QRect(10, 70, 171, 51))
        self.CreateDB.setObjectName("CreateDB")
        self.CheckConnection = QtWidgets.QPushButton(DBWindow)
        self.CheckConnection.setGeometry(QtCore.QRect(10, 130, 171, 51))
        self.CheckConnection.setObjectName("CheckConnection")
        self.InformationBrowser = QtWidgets.QTextBrowser(DBWindow)
        self.InformationBrowser.setGeometry(QtCore.QRect(190, 10, 301, 171))
        self.InformationBrowser.setObjectName("InformationBrowser")
        self.ConnectionSettings = QtWidgets.QPushButton(DBWindow)
        self.ConnectionSettings.setGeometry(QtCore.QRect(10, 10, 171, 51))
        self.ConnectionSettings.setObjectName("ConnectionSettings")

        self.retranslateUi(DBWindow)
        QtCore.QMetaObject.connectSlotsByName(DBWindow)

    def retranslateUi(self, DBWindow):
        _translate = QtCore.QCoreApplication.translate
        DBWindow.setWindowTitle(_translate("DBWindow", "База данных"))
        self.CreateDB.setText(_translate("DBWindow", " Создать базу данных"))
        self.CheckConnection.setText(_translate("DBWindow", "Проверить подключение\n"
"к базе данных"))
        self.ConnectionSettings.setText(_translate("DBWindow", "Настройки подключения"))
