# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_textWindow(object):
    def setupUi(self, textWindow):
        textWindow.setObjectName("textWindow")
        textWindow.resize(700, 500)
        textWindow.setMinimumSize(QtCore.QSize(700, 500))
        textWindow.setMaximumSize(QtCore.QSize(700, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        textWindow.setWindowIcon(icon)
        self.textEdit = QtWidgets.QTextEdit(textWindow)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 700, 311))
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(700, 500))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.listView = QtWidgets.QListView(textWindow)
        self.listView.setGeometry(QtCore.QRect(0, 350, 701, 151))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(textWindow)
        self.label.setGeometry(QtCore.QRect(5, 315, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(textWindow)
        QtCore.QMetaObject.connectSlotsByName(textWindow)

    def retranslateUi(self, textWindow):
        _translate = QtCore.QCoreApplication.translate
        textWindow.setWindowTitle(_translate("textWindow", "Дополнительные данные"))
        self.label.setText(_translate("textWindow", "Вложения:"))
